### ISSUE TITLE
"gnetsman/zabbix_api" not available now...

### ISSUE THREAD

**Issue by FrBillyD** [dnaeon/zabbix-ldap-sync#11]
Hi,
I want to use this tool but the api "gnetsman/zabbix_api" is not available... I try to use this with "lukecyca/pyzabbix" library, but it doesn't work :-1: 

Have you an answer to make it work with it ?

Thank you in advance ! :+1:

**Comment by dnaeon** [comment]
I wasn't aware that gnetsman/zabbix_api is now gone.. Thanks for letting me know of that.

This tool has been written when the lukecyca/pyzabbix was not present, and I should note that lukecyca/pyzabbix is way better than the gnetsman/zabbix_api (now gone anyways..).

Working with lukecyca/pyzabbix is actually easier, but I don't have enough spare time to refactor the code to use the new module at the moment, but if you do I'd be glad to merge a proposed PR.

**Comment by FrBillyD** [comment]
Thank you for your fast reply. Okay, I'll try to do something. I am a beginner in Python. :+1:

**Comment by FrBillyD** [comment]
J'ai trouvé une copie de l'API mais je ne sais pas si elle est à jour. J'ai testé, mais sans succès...
https://github.com/gescheit/scripts/tree/master/zabbix

I have this error : 
ldap.OPERATIONS_ERROR: {'info': '000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1', 'desc': 'Operations error'}

**Comment by dnaeon** [comment]
I'd really like to get rid of the gnetsman/zabbix_api

Moving forward with lukecyca/pyzabbix would be my preferred option, since this is the Python module that works pretty with Zabbix.

**Comment by FrBillyD** [comment]
Ok. I was looking for a quick fix but it missed :stuck_out_tongue:

**Comment by dnaeon** [comment]
Should be fixed by #14
