### ISSUE TITLE
Zabbix Running on SSL - Suport Unverified Certs

### ISSUE THREAD

**Issue by dneto82** [dnaeon/zabbix-ldap-sync#17]
Dear Friend,

First of all, thank you for you script.

I suggest add in you script, in L259

self.conn.session.verify = False

With this, is possible use Zabbix running over https with self-signed or unverified certificates 

Regards

**Comment by dnaeon** [comment]
@dneto82 thanks for reporting!

Can you please submit a pull request for this one?

Thanks,
Marin

**Comment by dnaeon** [comment]
Fixed in #21
