### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by oneautomate** [dnaeon/zabbix-ldap-sync#18]
Hi There,
I encountered an error when uid object is empty from our AD, and your script failed.
Can you please take a look?

(i added print str(uid))
# ./zabbix-ldap-sync-sli -f zabbix-ldap.conf
[('CN=first last,OU=Users,OU=Production,OU=###,DC=###,DC=######,DC=com', {'sAMAccountName': ['firs.last']})]
[('CN=swap,OU=Users,OU=Production,OU=###,DC=###,DC=######,DC=com', {'sAMAccountName': ['swap']})]
[]
Traceback (most recent call last):
  File "./zabbix-ldap-sync-sli", line 536, in <module>
    main()
  File "./zabbix-ldap-sync-sli", line 533, in main
    zabbix_conn.sync_users(config.ldap_uri, config.ldap_base, config.ldap_groups, config.ldap_user, config.ldap_pass, config.ldap_mail)
  File "./zabbix-ldap-sync-sli", line 411, in sync_users
    ldap_users = ldap_conn.get_group_members(eachGroup)
  File "./zabbix-ldap-sync-sli", line 121, in get_group_members
    dn, users = uid.pop()
IndexError: pop from empty list

**Comment by beatcracker** [comment]
Does solution from issue #16 works for you?

**Comment by dnaeon** [comment]
Fixed in #21
