### ISSUE TITLE
Unable to find group users, skipping group

### ISSUE THREAD

**Issue by lagrianitis** [dnaeon/zabbix-ldap-sync#25]
Hello,

I run ipaserver userdirecotry directory (based on openLdap). 

User DN looks like:
uid=user,cn=users,cn=acocunts,dc=ipavagrant

which is member of the group:

cn=ipausers,cn=groups,cn=acocunts,dc=ipavgrant

The idea is to set in the zabbix-ldap.conf file the group ipausers and then the script should fetch all users under this group and create them in zabbix.

The zabbix-ldap.conf file I use contains:

[ldap]
type = ipaserver
uri = ldap://1.1.1.2:389
base = cn=accounts,dc=ipavagrant
binduser = uid=admin,cn=users,cn=accounts,dc=ipavagrant
bindpass = test456
groups = ipausers

[zabbix]
server = http://1.1.1.1/zabbix
username = admin
password = test123

When I run the script, it is successfully establish connection to LDAP and Zabbix, it is creating the given group (ipausers) in Zabbix but it cannot match it with the LDAP directory group, so no users are created.

Here is the output:

[user@ipaserver1 ~]# python zabbix-ldap-sync  -f zabbix-ldap.conf
>>> Creating Zabbix group ipausers
>>> Group ipausers created with groupid 19
>>> Unable to find group ipausers, skipping group

Any help would be really appreciated!

**Comment by SmilingNavern** [comment]
Your group should be PosixGroup according to code: objectClass=posixGroup.

And please show output of ldapsearch command for cn=ipausers

**Comment by bilbo-the-hobbit** [comment]
hello,

i just submitted pull request 34 https://github.com/dnaeon/zabbix-ldap-sync/pull/34 if you want to test, it allow you to synchronize in posix and groupofnames mode

Cheers

**Comment by bilbo-the-hobbit** [comment]
Hello,

This is correct in pr #34 that have been merged, could you close it

Cheers

**Comment by dnaeon** [comment]
Thanks @bilbo-the-hobbit !
