### ISSUE TITLE
Update user media every time (if needed), not only when created user 

### ISSUE THREAD

**Issue by allburov** [dnaeon/zabbix-ldap-sync#27]
Update user media every time (if needed), not only when created user

**Comment by dnaeon** [comment]
Hey @allburov,

Thanks for reporting this one. Currently I don't have enough spare time to look into this one.

Care to send a patch with via PR with the fix for this?

Thanks,
Marin

**Comment by bilbo-the-hobbit** [comment]
hello,

i pushed pr #37 for this

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

as pr #37 as been merged we can close this
