### ISSUE TITLE
licence type

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [dnaeon/zabbix-ldap-sync#30]
Hello,

could you specify the licence type your are using, from the copyright header it seems a bsd licence, it would be great to add a license file into your sources

Cheers

**Comment by dnaeon** [comment]
Hey,

Yes, it is a BSD license.

I'll make sure to add a LICENSE file these days.

Regards,
Marin

**Comment by bilbo-the-hobbit** [comment]
ok great

**Comment by bilbo-the-hobbit** [comment]
This has been correct in PR #36, i'am closing it
