### ISSUE TITLE
Invalid DN Syntax

### ISSUE THREAD

**Issue by joaoluizmf** [dnaeon/zabbix-ldap-sync#46]
Hi, I'm trying to use you script, but I getting this error:

**Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 884, in <module>
    main()
  File "./zabbix-ldap-sync", line 881, in main
    config.media_opt)
  File "./zabbix-ldap-sync", line 605, in sync_users
    ldap_conn.connect()
  File "./zabbix-ldap-sync", line 69, in connect
    self.conn.simple_bind_s(self.ldap_user, self.ldap_pass)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 223, in simple_bind_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 514, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 521, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 106, in _ldap_call
    result = func(*args,**kwargs)
ldap.INVALID_DN_SYNTAX: {'info': 'invalid DN', 'desc': 'Invalid DN syntax'}**

Thanks.

**Comment by bilbo-the-hobbit** [comment]
Hello,

can you share your config file, as i have done most of the ldap code lately

Cheers

**Comment by joaoluizmf** [comment]
Sure. Here:

[ldap]
type = openldap
uri = ldap://X.X.X.X:389
base = dc=xx,dc=xx
binduser = xx
bindpass = xx
groups = xx

[ad]
filtergroup = (&(objectClass=group)(name=%s))
filteruser = (objectClass=user)(objectCategory=Person)
filterdisabled = (!(userAccountControl:1.2.840.113556.1.4.803:=2))
filtermemberof = (memberOf:1.2.840.113556.1.4.1941:=%s)
groupattribute = member
userattribute = sAMAccountName

[openldap]
type = groupofnames
filtergroup = (&(memberof=cn=xx,ou=group,dc=xx,dc=xx)(sambaacctflags=[U]))
filteruser = (&(memberof=cn=xx,ou=group,dc=xx,dc=xx)(sambaacctflags=[U]))
groupattribute = memberUid
userattribute = uid

[zabbix]
server = http://xx.xx.xx.xx
username = xx
password = xx

[user]
type = 3
url = http://xx.xx.xx.xx

[media]
description = Email

**Comment by scoopex** [comment]
Probably your problem does not exist anymore.
Please retest your problem with the current release and create a new issue at new location of the project https://github.com/zabbix-tooling/zabbix-ldap-sync.
