### ISSUE TITLE
Cannot connect to LDAP server error

### ISSUE THREAD

**Issue by SKUZ-ee** [dnaeon/zabbix-ldap-sync#47]
I have been trying to get this script to sync Zabbix with Active Directory and can't seem to get it to work. It successfully creates the group but it does not populate the created group with any members of the specified AD group. Here is the error that I keep getting.

Error:
Cannot connect to LDAP server: {'info': 'Error in the pull function.', 'desc': "Can't contact LDAP server"}

- LDAP authentication is working with Zabbix
- ldapsearch can successfully query AD names

Can you please help me and see what I am doing wrong?

===============
zabbix-ldap-users.conf
[ldap]
type = activedirectory
uri = ldaps://192.168.1.102:389/
base = OU=User Accounts,DC=ad,DC=home,DC=lan
binduser = ad\zabbixuser
bindpass = password123
groups = Zabbix_Users

[ad]
filtergroup = (&(objectClass=group)(name=%s))
filteruser = (objectClass=user)(objectCategory=Person)
filterdisabled = (!(userAccountControl:1.2.840.113556.1.4.803:=2))
filtermemberof = (memberOf:1.2.840.113556.1.4.1941:=%s)
groupattribute = member
userattribute = sAMAccountName

[openldap]
type = posix
filtergroup = (&(objectClass=posixGroup)(cn=%s))
filteruser = (&(objectClass=posixAccount)(uid=%s))
groupattribute = memberUid
userattribute = uid

[zabbix]
server = http://192.168.1.114/zabbix/
username = zabbixuser
password = password123

[user]
type = 1

[media]
description = Email

==========
verbose output:
root@zabbix:/opt/zabbix-ldap-sync# ./zabbix-ldap-sync -f zabbix-ldap-users.conf --verbose
2016-12-29 01:57:13,494 - INFO - JSON-RPC Server Endpoint: http://192.168.1.114/zabbix//api_jsonrpc.php
2016-12-29 01:57:13,494 - INFO - JSON-RPC Server Endpoint: http://192.168.1.114/zabbix//api_jsonrpc.php
2016-12-29 01:57:13,495 - DEBUG - Sending: {
    "params": {
        "password": "password123",
        "user": "zabbixuser"
    },
    "jsonrpc": "2.0",
    "method": "user.login",
    "id": 0
}
2016-12-29 01:57:13,495 - DEBUG - Sending: {
    "params": {
        "password": "password123",
        "user": "zabbixuser"
    },
    "jsonrpc": "2.0",
    "method": "user.login",
    "id": 0
}
2016-12-29 01:57:13,498 - DEBUG - Starting new HTTP connection (1): 192.168.1.114
2016-12-29 01:57:13,733 - DEBUG - http://192.168.1.114:80 "POST /zabbix//api_jsonrpc.php HTTP/1.1" 200 68
2016-12-29 01:57:13,735 - DEBUG - Response Code: 200
2016-12-29 01:57:13,735 - DEBUG - Response Code: 200
2016-12-29 01:57:13,747 - DEBUG - Response Body: {
    "jsonrpc": "2.0",
    "result": "ca9dc2ca0d3a06289506c1eaa7a1ca76",
    "id": 0
}
2016-12-29 01:57:13,747 - DEBUG - Response Body: {
    "jsonrpc": "2.0",
    "result": "ca9dc2ca0d3a06289506c1eaa7a1ca76",
    "id": 0
}
2016-12-29 01:57:13,748 - DEBUG - Sending: {
    "params": {
        "status": 0,
        "output": "extend"
    },
    "jsonrpc": "2.0",
    "method": "usergroup.get",
    "auth": "ca9dc2ca0d3a06289506c1eaa7a1ca76",
    "id": 1
}
2016-12-29 01:57:13,748 - DEBUG - Sending: {
    "params": {
        "status": 0,
        "output": "extend"
    },
    "jsonrpc": "2.0",
    "method": "usergroup.get",
    "auth": "ca9dc2ca0d3a06289506c1eaa7a1ca76",
    "id": 1
}
2016-12-29 01:57:13,759 - DEBUG - http://192.168.1.114:80 "POST /zabbix//api_jsonrpc.php HTTP/1.1" 200 431
2016-12-29 01:57:13,760 - DEBUG - Response Code: 200
2016-12-29 01:57:13,760 - DEBUG - Response Code: 200
2016-12-29 01:57:13,761 - DEBUG - Response Body: {
    "jsonrpc": "2.0",
    "result": [
        {
            "usrgrpid": "7",
            "gui_access": "0",
            "debug_mode": "1",
            "name": "Zabbix administrators",
            "users_status": "0"
        },
        {
            "usrgrpid": "11",
            "gui_access": "0",
            "debug_mode": "1",
            "name": "Enabled debug mode",
            "users_status": "0"
        },
        {
            "usrgrpid": "12",
            "gui_access": "2",
            "debug_mode": "0",
            "name": "No access to the frontend",
            "users_status": "0"
        },
        {
            "usrgrpid": "25",
            "gui_access": "0",
            "debug_mode": "0",
            "name": "NMS_Users",
            "users_status": "0"
        }
    ],
    "id": 1
}
2016-12-29 01:57:13,761 - DEBUG - Response Body: {
    "jsonrpc": "2.0",
    "result": [
        {
            "usrgrpid": "7",
            "gui_access": "0",
            "debug_mode": "1",
            "name": "Zabbix administrators",
            "users_status": "0"
        },
        {
            "usrgrpid": "11",
            "gui_access": "0",
            "debug_mode": "1",
            "name": "Enabled debug mode",
            "users_status": "0"
        },
        {
            "usrgrpid": "12",
            "gui_access": "2",
            "debug_mode": "0",
            "name": "No access to the frontend",
            "users_status": "0"
        },
        {
            "usrgrpid": "25",
            "gui_access": "0",
            "debug_mode": "0",
            "name": "NMS_Users",
            "users_status": "0"
        }
    ],
    "id": 1
}
Cannot connect to LDAP server: {'info': 'Error in the pull function.', 'desc': "Can't contact LDAP server"}

**Comment by dnaeon** [comment]
@bilbo-the-hobbit can you have a look at this one?

**Comment by bilbo-the-hobbit** [comment]
hello,

sure, i'am in holidays right now but will look about it on my retrun around 4 january

Cheers

**Comment by kaitik** [comment]
I see you use LDAPS and port 389, try to use 636 instead.

**Comment by scoopex** [comment]
Problem seems to be originated in the wrong port, no feedback for almost one year.
Closing this problem, please reopen with additional information.
