### ISSUE TITLE
Problem if user already exists and has lowercase alias

### ISSUE THREAD

**Issue by banzayats** [dnaeon/zabbix-ldap-sync#48]
Hello.
Thank you for the great script!
We found some unexpected behavior.

For example my account is already in Zabbix, but the script throws the exception:
```
>>> Creating user Vadim.K, member of Zabbix group monitoring-access
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 815, in <module>
    main()
  File "./zabbix-ldap-sync", line 812, in main
    config.media_opt)
  File "./zabbix-ldap-sync", line 577, in sync_users
    self.create_user(user, zabbix_grpid, user_opt)
  File "./zabbix-ldap-sync", line 454, in create_user
    result = self.conn.user.create(user)
  File "/usr/local/lib/python2.7/dist-packages/pyzabbix/__init__.py", line 157, in fn
    args or kwargs
  File "/usr/local/lib/python2.7/dist-packages/pyzabbix/__init__.py", line 134, in do_request
    raise ZabbixAPIException(msg, response_json['error']['code'])
pyzabbix.ZabbixAPIException: (u'Error -32602: Invalid params., User with alias "Vadim.K" already exists.', -32602)
```
`zabbix_all_users` contains my user name in lowercase (_vadim.k_) but in AD it is "_Vadim.K_". So the script tries to create the existing user.

I know that there is the parameter `--lowercase` which creates AD user names as lowercase. But if someone will accidently add something like _UseR.n_ - the script will stop to work.

Maybe it's better to convert all aliases lowercase and then compare them?

**Comment by mths0x5f** [comment]
I confirm this issue.

**Comment by dnaeon** [comment]
@bilbo-the-hobbit care to look into this one?
