### ISSUE TITLE
Specifying [ad] and [openldap] sections should not be mandatory

### ISSUE THREAD

**Issue by mths0x5f** [dnaeon/zabbix-ldap-sync#50]
There's no reason having to copy-n-paste them when they have default values.

**Comment by dnaeon** [comment]
Please submit a PR to get this updated.

I'm not paying close attention to this project anymore due to other projects I'm working on, so I'd appreciate if someone steps in and volunteers to maintain it.

**Comment by bilbo-the-hobbit** [comment]
hello,

what do you mean by copy paste the config file contains all you need from scratch ?

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

i quite busy myself by as some customer depend on it our company could help mainting it here

Cheers

**Comment by dnaeon** [comment]
The new location of the project is https://github.com/zabbix-tooling/zabbix-ldap-sync

In case this is still needed, please consider posting an issue there.
