### ISSUE TITLE
Users being skipped and domain users doesn't sync anyone

### ISSUE THREAD

**Issue by elvar152** [dnaeon/zabbix-ldap-sync#51]
Hello,

I am having an issue where various users are skipped which I can see exist in the group and are not disabled. Also, for whatever reason I am unable to sync any users from the "Domain Users" group. Any suggestions? I am using version 0.1.1.

Cheers,

**Comment by elvar152** [comment]
I think I resolved the issue with certain users being skipped by disabling recursive searching but the domain users group issue is still present.

Cheers,

**Comment by scoopex** [comment]
Probably your problem does not exist anymore.
Please retest your problem with the current release and create a new issue at new location of the project https://github.com/zabbix-tooling/zabbix-ldap-sync.
