### ISSUE TITLE
TypeError: 'ZabbixAPIObjectClass' object is not callable

### ISSUE THREAD

**Issue by cherbunin** [dnaeon/zabbix-ldap-sync#54]
Faced with error:
# ./zabbix-ldap-sync -f zabbix-ldap.conf
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 884, in <module>
    main()
  File "./zabbix-ldap-sync", line 870, in main
    zabbix_conn.connect(nocheckcertificate)
  File "./zabbix-ldap-sync", line 377, in connect
    self.conn.login(self.username, self.password)
TypeError: 'ZabbixAPIObjectClass' object is not callable
Tell me, please, where there can be a mistake?

**Comment by scoopex** [comment]
It sems that your installation of pyzabbix not seems to be complete.
I added some documentation.

Please review section "Setup virtualenv" at the new location of the project https://github.com/zabbix-tooling/zabbix-ldap-sync and open a new report at the new project.
