### ISSUE TITLE
Sync over https

### ISSUE THREAD

**Issue by Xeiro** [dnaeon/zabbix-ldap-sync#55]
Hello,

I do have zabbix configured to run in https mode and I am redirecting all http to https. This is what I get if I run sync script:

[ourservername zabbix-ldap-sync]# ./zabbix-ldap-sync -d -l -n -s -f /etc/zabbix-ldap-sync/zabbix-ldap-SuperAdministrators.conf
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 884, in <module>
    main()
  File "./zabbix-ldap-sync", line 870, in main
    zabbix_conn.connect(nocheckcertificate)
  File "./zabbix-ldap-sync", line 377, in connect
    self.conn.login(self.username, self.password)
  File "/usr/lib/python2.7/site-packages/pyzabbix/__init__.py", line 70, in login
    self.auth = self.user.login(user=user, password=password)
  File "/usr/lib/python2.7/site-packages/pyzabbix/__init__.py", line 157, in fn
    args or kwargs
  File "/usr/lib/python2.7/site-packages/pyzabbix/__init__.py", line 109, in do_request
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ourzabbixname/zabbix/api_jsonrpc.php

This is in my *conf file:
[zabbix]
server = https://ourzabbixname/zabbix
username = username
password = password

I tested to set up http there too, but still not working.

Please can you test this?

Tyvm

**Comment by dnaeon** [comment]
Hi,

I'm no longer maintaining this project actively. If there's someone that wants to take ownership of this project, please let me know, so I can transfer ownership.

**Comment by smoghaddas** [comment]
Hi,
Special thanks for your project.
please write this at README.md

> Hi,
> 
> I'm no longer maintaining this project actively. If there's someone that wants to take ownership of this project, please let me know, so I can transfer ownership.

**Comment by scoopex** [comment]
This problem is solved because my setup utilizes HTTPS and works perfectly.
If you still experience problems, please provide detailed information
(i.e. error/access logfile data of the webserver, detailed trace of the ssl handshake, ...)

**Comment by scoopex** [comment]
I close this problem, pleas reopen with detailed information.
