### ISSUE TITLE
Update media trying to update users that aren't in group.

### ISSUE THREAD

**Issue by tcatut** [dnaeon/zabbix-ldap-sync#60]
I'm using a fresh install as of today, with latest release.  I get the output below.  It seems like the script knows this user isn't part of the group; but it's still trying to sync the media information, which throws an exception.  I don't want to remove orphaned users; as there are a few people manually added to the Zabbix group but they aren't in the AD group.

```
>>> Users in group vasDev which are not found in LDAP group:
 * testuser
 * aeldred
 * ntitare

>>> Updating/create user media for "testuser", update "Email"
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 961, in <module>
    main()
  File "./zabbix-ldap-sync", line 958, in main
    config.media_opt)
  File "./zabbix-ldap-sync", line 728, in sync_users
    sendto = ldap_conn.get_user_media(ldap_users[eachUser], ldap_media).decode("utf8")
KeyError: 'testuser'
```

**Comment by tcatut** [comment]
Here's the simple fix; but maybe you want to do something different here?

index ee5b46e..74adb3d 100755
--- a/zabbix-ldap-sync
+++ b/zabbix-ldap-sync
@@ -724,6 +724,9 @@ class ZabbixConn(object):
                 zabbix_group_users = self.get_group_members(zabbix_grpid)
 
             for eachUser in set(zabbix_group_users):
+                if eachUser in extra_users:
+                    print('>>> Skipping user "%s"' % eachUser)
+                    continue
                 print('>>> Updating/create user media for "%s", update "%s"' % (eachUser, media_description))
                 sendto = ldap_conn.get_user_media(ldap_users[eachUser], ldap_media).decode("utf8")

**Comment by tcatut** [comment]
I just tried to make a pull request for this change; but I'm getting permission denied errors.

**Comment by dnaeon** [comment]
@scoopex can you look into this one?

**Comment by scoopex** [comment]
@tcatut did you owned permissions on this repo or do to invoke the pull request from your own fork?

**Comment by scoopex** [comment]
Probably your problem does not exist anymore.
Please retest your problem with the current release and create a new issue at new location of the project https://github.com/zabbix-tooling/zabbix-ldap-sync.
