### ISSUE TITLE
AttributeError: 'LDAPConn' object has no attribute 'openldap_type'

### ISSUE THREAD

**Issue by Volont84** [dnaeon/zabbix-ldap-sync#62]
My config:
[ldap]
type = openldap
uri = ldaps://myserver.com:10636
base = o=main
binduser = uid=admin,ou=system
bindpass = pass
groups = test

[openldap]
type = groupofnames
filtergroup = (&(objectClass=groupOfUniqueNames)(cn=%s))
filteruser = (&(objectClass=inetOrgPerson)(uid=%s))
groupattribute = cn
userattribute = uid

When i trying to sync i am getting error 

Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 90, in <module>
    main()
  File "./zabbix-ldap-sync", line 87, in main
    zabbix_conn.sync_users()
  File "...zabbix-ldap-sync/lib/zabbixconn.py", line 344, in sync_users
    ldap_users = self.ldap_conn.get_group_members(eachGroup)
  File "...zabbix-ldap-sync/lib/ldapconn.py", line 181, in get_group_members
    if self.openldap_type == "groupofnames":
AttributeError: 'LDAPConn' object has no attribute 'openldap_type'

Maybe you can tell me where am I wrong?

**Comment by dnaeon** [comment]
@scoopex can you have a look at this one?

**Comment by Volont84** [comment]
oops, i had commented string
self.memberof_filter = config.ldap_memberof_filter
in ldapconn.py

But when string is uncommented there is another error
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 90, in <module>
    main()
  File "./zabbix-ldap-sync", line 79, in main
    ldap_conn = LDAPConn(config)
  File ".../zabbix-ldap-sync/lib/ldapconn.py", line 24, in __init__
    self.memberof_filter = config.ldap_memberof_filter
AttributeError: 'ZabbixLDAPConf' object has no attribute 'ldap_memberof_filter'

**Comment by scoopex** [comment]
It seems that you invoked the sync using "--recursive". From my point of view is is only supported/needed on windows active directory, right?

See: https://github.com/dnaeon/zabbix-ldap-sync/commit/d92fc97e58d3058a093cda872dcb925ee6088e71

**Comment by Volont84** [comment]
No, I don`t use "-r" just 
./zabbix-ldap-sync -d -f zabbix-ldap.conf 

After testing your changes get error

Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 90, in <module>
    main()
  File "./zabbix-ldap-sync", line 87, in main
    zabbix_conn.sync_users()
  File ".../zabbix-ldap-sync/lib/zabbixconn.py", line 344, in sync_users
    ldap_users = self.ldap_conn.get_group_members(eachGroup)
  File "...zabbix-ldap-sync/lib/ldapconn.py", line 182, in get_group_members
    if self.openldap_type == "groupofnames":
AttributeError: 'LDAPConn' object has no attribute 'openldap_type'

**Comment by dnaeon** [comment]
Re-opening issue as it is not yet solved.

**Comment by Volont84** [comment]
Didn't work. Same error.

**Comment by scoopex** [comment]
Executed "git pull" ?

Can you send me the following data by mail: ms-github@256bit.org
* an anonymized  configuration
* the exact output
* the exact output with "--verbose"

**Comment by Volont84** [comment]
Well it was hard but yes, I executed "git pull" )))
Send to you a mail. And thanks for your time.

**Comment by scoopex** [comment]
Just to be sure :-) Thanks for providing additional information by mail.

i made some modifications which might help to solve your problem.

Please be aware that the development repo switched to  https://github.com/dnaeon/zabbix-ldap-sync

You can switchover by invoking:
```
git remote set-url origin git@github.com:zabbix-tooling/zabbix-ldap-sync.git # or
git remote set-url origin https://github.com/zabbix-tooling/zabbix-ldap-sync.git
```

Please provide feedback if there are still problems....

**Comment by scoopex** [comment]
solved by Анатолий, many thanks.

see commit f2b7dbccd769627a58d5b969e8c9897338734962 at https://github.com/zabbix-tooling/zabbix-ldap-sync
