### ISSUE TITLE
UnboundLocalError: local variable 'user' referenced before assignment

### ISSUE THREAD

**Issue by sir-hawk32** [dnaeon/zabbix-ldap-sync#63]
The problem with synchronizing the group is where 1 user (presumably this is the reason)
[debug.txt](https://github.com/dnaeon/zabbix-ldap-sync/files/2044770/debug.txt)

**Comment by dnaeon** [comment]
Please consider posting this issue to https://github.com/zabbix-tooling/zabbix-ldap-sync

The repo has been moved there.
